# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: 
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    admin:
                        password: $2y$12$ScL.IkAhaL/sNohzD0GLj.o7Yq9YGbC0OCwKov030v4KS4V.Etb9e
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            
            logout: 
                path: /logout
                target: /
            
    access_control:
        - { path: ^/api/doc, roles: ROLE_ADMIN }
