# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    upload.service:
        class: AppBundle\Upload\UploadFile
        arguments:
            - '%kernel.root_dir%'
            
    mailer.contact_mailer:
        class: AppBundle\Mailer\ContactMailer
        arguments: 
            - '%kernel.root_dir%'
            - '@templating'
            - '@mailer'
            - '%mailer_from_email%'
            - '%mailer_to_email%'

    mailer.mailer_website:
        class: AppBundle\Mailer\MailerWebsite
        arguments: 
            - '%kernel.root_dir%'
            - '@templating'
            - '@mailer'
            - '%mailer_from_email%'
            - '%mailer_to_email%'
